OPENCTI_ADMIN_EMAIL=*email and username for logging into OpenCTI*
OPENCTI_ADMIN_PASSWORD=*Password - MAKE IT SECUURE!!! *
OPENCTI_ADMIN_TOKEN=*Generate Unique GUID - Use: https://www.uuidgenerator.net/guid*
OPENCTI_BASE_URL=https://fqdn-of-portinaer:8080
MINIO_ROOT_USER=*redacted1*
MINIO_ROOT_PASSWORD=*redacted1*
RABBITMQ_DEFAULT_USER=*redacted2*
RABBITMQ_DEFAULT_PASS=*redacted2*
CONNECTOR_EXPORT_FILE_STIX_ID=*Redacted_GUID1*
CONNECTOR_EXPORT_FILE_CSV_ID=*Redacted_GUID2*
CONNECTOR_EXPORT_FILE_TXT_ID=*Redacted_GUID3*
CONNECTOR_IMPORT_FILE_STIX_ID=*Redacted_GUID4*
CONNECTOR_IMPORT_DOCUMENT_ID=*Redacted_GUID5*
CONNECTOR_ANALYSIS_ID=*Redacted_GUID5*
SMTP_HOSTNAME=*your_SMTP_relay*
ELASTIC_MEMORY_SIZE=8G #Scale to your needs
OPENCTI_URL=https://fqdn-of-portinaer:8080
OPENCTI_KEY_PATH=/etc/ssl/certs/opencti-certs/opencti.key
OPENCTI_CRT_PATH=/etc/ssl/certs/opencti-certs/opencti.crt
OPENCTI_HEALTHCHECK_ACCESS_KEY=*Redacted_API_Key1*
ALIENVAULT_API_KEY=*Redacted_API_Key2*
CVE_API_KEY=*Redacted_API_Key3*
NIST_API_KEY=*Redacted_API_Key4*
VIRUSTOTAL_LIVEHUNT_NOTIFICATIONS_API_KEY=*Redacted_API_Key5*
